apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  {{ if .Values.managedMetadataStore.enabled }}
  type: ExternalName
  externalName: {{ .Values.managedMetadataStore.dbHost }}
  {{ else }}
  selector: 
    app: mysql
    app.kubernetes.io/name: {{ .Release.Name }}
  {{ end }}
  ports:
    - port: 3306
---
{{ if .Values.managedMetadataStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credential
  labels:
    app: mysql-credential
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.managedMetadataStore.dbUsername | b64enc | quote}}
  password: {{ .Values.managedMetadataStore.dbPassword | b64enc | quote}}
{{ else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccountName: mysql
      containers:
        - name: mysql
          image: "{{ .Values.repositories.mysql }}:{{ .Values.pipelinesVersion }}"
          args:
          # https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_ignore-db-dir
          # Ext4, Btrfs etc. volumes root directories have a lost+found directory that should not be treated as a database.
          - --ignore-db-dir=lost+found
          - --datadir
          - /var/lib/mysql
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
          resources:
            requests:
              cpu: 100m
              memory: 800Mi
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
{{ end }}
