{{ if .Values.frontend.isExposed }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: lb-targetgroup-ml-pipeline-ui
spec:
  serviceRef:
    name: ml-pipeline-ui
    port: 80
  targetGroupARN: {{ .Values.frontend.targetGroupARN | quote }}
  targetType: instance
{{ end }}
---
{{ if .Values.apiserver.isExposed }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: lb-targetgroup-ml-pipeline
spec:
  serviceRef:
    name: ml-pipeline
    port: 8888
  targetGroupARN: {{ .Values.apiserver.targetGroupARN | quote }}
  targetType: instance
{{ end }}