enableJupyterLab: true
restartable: true
chownHome: true

image:
  useCustomImage: false
  preBuilt: jupyter/tensorflow-notebook:lab-3.0.14
  custom: nathaliamdc/tensorflow-notebook:lab-3.0.14

user:
  name: nathalia
  grantSudo: false

elasticFileSystem:
  id:
  capacity: 2Gi # Required by Kubernetes but meaningless to EFS because it is elastic (has no predefined capacity)
  mountPath: "/home/nathalia" # Same as home directory

service:
  isExposed: 
  targetGroupARN:
  nodePort: