apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-gateway
  labels:
    app: kernel-gateway
    app.kubernetes.io/name: kernel-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kernel-gateway
  template:
    metadata:
      labels:
        app: kernel-gateway
        app.kubernetes.io/name: kernel-gateway
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: kernel-gateway
        image: {{ .Values.containerImage }}
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: 500Mi
            cpu: 250m