apiVersion: v1
kind: Service
metadata:
  name: kernel-gateway
  labels:
    app.kubernetes.io/name: kernel-gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: {{ .Values.nodePort }}
  selector:
    app: kernel-gateway
    app.kubernetes.io/name: kernel-gateway