apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
    app.kubernetes.io/name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter
  template:
    metadata:
      labels:
        app: jupyter
        app.kubernetes.io/name: jupyter
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: jupyter
        image: {{ if .Values.image.useCustomImage }} {{ .Values.image.custom }} {{ else }} {{ .Values.image.preBuilt }} {{ end }}
        ports:
        - containerPort: 8888
        env:
        {{ if .Values.enableJupyterLab }}
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        {{ end }}
        - name: RESTARTABLE
          value: {{ if .Values.restartable }} "yes" {{ else }} "no" {{ end }}
        - name: NB_USER
          value: {{ .Values.user.name | quote }}
        - name: GRANT_SUDO
          value: {{ if .Values.user.grantSudo }} "yes" {{ else }} "no" {{ end }}
        - name: CHOWN_HOME
          value: {{ if .Values.chownHome }} "yes" {{ else }} "no" {{ end }}
        command:
          - /bin/bash
          - -c
          - |
            start.sh jupyter lab --ServerApp.token='' --ServerApp.ip='0.0.0.0'
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
        volumeMounts:
        - name: persistent-storage
          mountPath: {{ .Values.elasticFileSystem.mountPath }}
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim