apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app.kubernetes.io/name: jupyter
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: jupyter
    app.kubernetes.io/name: jupyter