{{ if .Values.service.isExposed }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: lb-targetgroup-jupyter
  labels:
    app: lb-targetgroup-jupyter
    app.kubernetes.io/name: jupyter
spec:
  serviceRef:
    name: jupyter
    port: 8888
  targetGroupARN: {{ .Values.service.targetGroupARN | quote }}
  targetType: instance
{{ end }}